interface TrophyItem {
    url: string;
    title: string;
    description: string;
}

export const TrophyText: TrophyItem[] = [
    { url: "platino", title: "Sparking!", description: "Has obtenido todos los trofeos" },
    { url: "bronce", title: "El sabor de la victoria", description: "Has ganado 10 combates." },
    { url: "plata", title: "Racha triunfal", description: "Has ganado 100 combates." },
    { url: "bronce", title: "Enfrentamiento con nuevos rivales", description: "Has luchado en 3 combates en línea" },
    { url: "plata", title: "Rivales conectados", description: "Has luchado en 100 combates en línea" },
    { url: "bronce", title: "Preparando el combate", description: "Has personalizado un personaje" },
    { url: "plata", title: "Confrontación predestinada", description: "Has visto 20 escenas de diálogos especiales." },
    { url: "plata", title: "Un talento para luchar", description: "Has visto 20 remates especiales." },
    { url: "bronce", title: "Campeón del torneo mundial", description: "Has conseguido la victoria en el Torneo Mundial." },
    { url: "bronce", title: "Campeón de los juegos de Célula", description: "Has conseguido la victoria en los Juegos de Célula." },
    { url: "bronce", title: "Maestro del torneo del más allá", description: "Has conseguido la victoria en el Torneo del más allá." },
    { url: "bronce", title: "Dominador del torneo de destructores", description: "Has conseguido la victoria en el Torneo de Destructores." },
    { url: "bronce", title: "Líder del torneo de poder", description: "Has conseguido la victoria en el Torneo de Poder." },
    { url: "bronce", title: "¡Nunca es suficiente!", description: "Has completado la saga de Son Goku." },
    { url: "bronce", title: "Codo con codo", description: "Has completado el capítulo 'Codo con codo' de la saga de Son Goku." },
    { url: "bronce", title: "Superando los límites", description: "Has completado el capítulo 'Superando los límites' de la saga de Son Goku." },
    { url: "bronce", title: "El futuro cambiante", description: "Has completado el capítulo 'El futuro cambiante' de la saga de Son Goku." },
    { url: "bronce", title: "Métete en tus asuntos...", description: "Has completado la saga de Vegeta." },
    { url: "bronce", title: "Vínculo parental", description: "Has completado el capítulo 'Vínculo parental' de la saga de Vegeta." },
    { url: "bronce", title: "Primer lugar", description: "Has completado el capítulo 'Primer lugar' de la saga de Vegeta." },
    { url: "bronce", title: "¡Ya no soy un crío!", description: "Has completado la saga de Son Gohan." },
    { url: "bronce", title: "El guerrero más fuerte", description: "Has completado el capítulo 'El guerrero más fuerte' de la saga de Son Gohan." },
    { url: "bronce", title: "Perdona por hacerte esperar...", description: "Has completado la saga de Piccolo." },
    { url: "bronce", title: "La enseñanza de un mentor", description: "Has completado el capítulo 'La enseñanza de un mentor' de la saga de Piccolo." },
    { url: "bronce", title: "Dios o mortal, ¡No perderé!", description: "Has completado la saga de Trunks del futuro." },
    { url: "bronce", title: "Esperanza resplandeciente", description: "Has completado el capítulo 'Esperanza resplandeciente' de la saga de Trunks del futuro." },
    { url: "bronce", title: "Orgullo heredado", description: "Has completado el capítulo 'Orgullo heredado' de la saga de Trunks del futuro." },
    { url: "bronce", title: "Embarcando hacia el mañana", description: "Has completado el capítulo 'Embarcando hacia el mañana' de la saga de Trunks del futuro." },
    { url: "bronce", title: "El cruel emperador", description: "Has completado la saga de Freezer." },
    { url: "bronce", title: "El ejército de Freezer se une al combate", description: "Has completado el capítulo 'El ejército de Freezer se une al combate' de la saga de Freezer." },
    { url: "bronce", title: "Plan 'cero mortales'", description: "Has completado la saga de Goku Black." },
    { url: "bronce", title: "Prueba de la justicia", description: "Has completado el capítulo 'Prueba de la justicia' de la saga de Goku Black." },
    { url: "bronce", title: "La fuerza es justicia", description: "Has completado la saga de Jiren." },
    { url: "bronce", title: "Fuerza verdadera", description: "Has completado el capítulo 'Fuerza verdadera' de la saga de Jiren." },
    { url: "oro", title: "Omnisciente", description: "Has completado 21 sagas en Combate de episodio." },
    { url: "oro", title: "Combate de ensueño", description: "Has completado 30 combates adicionales." },
    { url: "bronce", title: "¡Manifiéstate, Shenron!", description: "Has invocado a Shenron y se te ha concedido un deseo." },
    { url: "bronce", title: "¡Manifiéstate, Porunga!", description: "Has invocado a Porunga y se te ha concedido un deseo." },
    { url: "plata", title: "¡Manifiéstate, Súper Shenron!", description: "Has invocado a Súper Shenron y se te ha concedido un deseo." },
    { url: "bronce", title: "Guerrero novato", description: "Has alcanzado el nivel de jugador 5." },
    { url: "plata", title: "Guerrero experto", description: "Has alcanzado el nivel de jugador 20." },
    { url: "plata", title: "Zenionario", description: "Has ganado un total de 1 000 000 de zeni." },
    { url: "plata", title: "Derrochador", description: "Has gastado un total de 1 000 000 de zeni." },
    { url: "bronce", title: "Algo es algo", description: "Has conseguido 10 objetos de destreza diferentes." },
    { url: "plata", title: "Preparado para todo", description: "Has conseguido 50 objetos de destreza diferentes." },
    { url: "bronce", title: "Presumiendo", description: "Has editado por completo una tarjeta de jugador." },
    { url: "bronce", title: "Coleccionista de títulos novato", description: "Has ganado un título." },
    { url: "plata", title: "Coleccionista de títulos", description: "Has ganado 100 títulos." }
];
